### ISSUE TITLE
There should be a possibility to hide e.g. a screenshots directory. 

### ISSUE THREAD

**Issue by wintermeyer** [hybridgroup/GitHub-Wikifier#1]
BTW: Great work! :-)

**Comment by MarioRicalde** [comment]
Excellent Idea, will add it soon, it makes a lot of sense.

Will probably go with a assets directory to begin.

And then think if I should add something similar to `.gitignore`, but for Wikifier.

**Comment by MarioRicalde** [comment]
Will assume fixed, until we need more directories.
