### ISSUE TITLE
Absolute path

### ISSUE THREAD

**Issue by johanlaidlaw** [hybridgroup/GitHub-Wikifier#14]
The script creates absolute paths for the links, which is of course a problem when I push to GitHub. I'm on a mac and use standard .md text files. I have tried to clone my repo to different dirs on my machine, but same problem.

Any help would be appreciated.

**Comment by MarioRicalde** [comment]
Is the repo public? can you point us to the repo wiki to see how the file structure looks?

**Comment by johanlaidlaw** [comment]
It is a private repo, but I have just setup a public one, same problem:

https://github.com/johanlaidlaw/Documentation/wiki

**Comment by MarioRicalde** [comment]
https://github.com/hybridgroup/GitHub-Wikifier/wiki/1.1.-Naming-Guidelines

Files must end with `.md`, I added that to `1.1-Introduction` and it worked.

**Comment by johanlaidlaw** [comment]
(facepalm) I was sure I did that.
Sorry about taking your time and thanks for the help
