### ISSUE TITLE
error: cannot run .git/hooks/pre-commit: ?? ???? ????? ????

### ISSUE THREAD

**Issue by revivent** [hybridgroup/GitHub-Wikifier#15]
when i input below command on terminal. (Ubuntu 13.04)

```
git add *
git add .
git commit -m "$message"
```

i got an error,

`error: cannot run .git/hooks/pre-commit: ?? ???? ????? ????`

i also use non-elglish character. so i apply https://github.com/hybridgroup/GitHub-Wikifier/pull/13 .. but got still same error.

what can i do??

**Comment by solojavier** [comment]
Are you using zsh terminal?

**Comment by jgranick** [comment]
The README should really say that `zsh` needs to be installed, or (perhaps) the script could check and provide an error message :)

You do not need to be using `zsh` for it to work, but you do need to install the package:

```
sudo apt-get install zsh
```

**Comment by solojavier** [comment]
Added in this commit: https://github.com/hybridgroup/GitHub-Wikifier/commit/f4c2dbb33a76578f6825029ded8133e25a1f4315

What do you think?

**Comment by jgranick** [comment]
Looks good, thanks! :)
