### ISSUE TITLE
Double digit bug

### ISSUE THREAD

**Issue by newtriks** [hybridgroup/GitHub-Wikifier#16]
It appears that if you use double digits then the lists render in the incorrect order e.g.

```
    ### [[☰|1.-First.md]] 1. First.md

    ### [[☰|10.-Tenth.md]] 10. Tenth.md

    ### [[☰|2.-Second.md]] 10. Second.md
```

**Comment by MarioRicalde** [comment]
This was just fixed, sorry for the delay https://github.com/hybridgroup/GitHub-Wikifier/commit/d9dd58aa6ca1dd1f3d6fc395c1ce772df644de0a

**Comment by newtriks** [comment]
Nice one thanks
