### ISSUE TITLE
Question about How to use 

### ISSUE THREAD

**Issue by shinokada** [hybridgroup/GitHub-Wikifier#18]
In the first part of How to use you wrote,

```
Clone your wiki git repo
https://github.com/hybridgroup/GitHub-Wikifier/wiki/_access
```

Is it a typo? 

Should it be `https://github.com/yourname/reponame.wiki.git`?

**Comment by trev** [comment]
Yes, that's correct.

**Comment by solojavier** [comment]
Resolved in this commit: https://github.com/hybridgroup/GitHub-Wikifier/commit/094ea4acd5d8f7e47ec002d90b982aeb6b027faf .. Thanks
