### ISSUE TITLE
Use of * (<li>) in Home.md instead of <br>

### ISSUE THREAD

**Issue by wintermeyer** [hybridgroup/GitHub-Wikifier#2]
I think the use of \* (<li>) in Home.md would increase the readability. Example:

```
### [[1. What ever]]
* [[Weather in LA]]
* [[Weather in SFO]]
* [[Weather in NY]]
```

**Comment by MarioRicalde** [comment]
I'm going to give this a second try. I actually used bullets on the first iteration, but it broke the "good practice" of adding a number in front of the file to specify order.

I have an idea on how to implement this, I think.

**Comment by MarioRicalde** [comment]
It looks pretty now: https://github.com/kuroir/GitHub-Wikifier/wiki
