### ISSUE TITLE
Order problem

### ISSUE THREAD

**Issue by shinokada** [hybridgroup/GitHub-Wikifier#20]
As you can see in the image the order more than 10 come after 1, like 1, 10, 11, 12, 2, 3 etc.

Is there any fix for this?

![screen shot 2014-02-16 at 14 16 00](https://f.cloud.github.com/assets/147320/2179684/8c4b19ec-96c9-11e3-9500-59d15af1b761.png)

**Comment by MarioRicalde** [comment]
I had to dig really deep into my emails to notice this, but now it's fixed!

@shinokada 申し訳ございません

**Comment by shinokada** [comment]
Thanks for your fix. ありがとうございました。Now how can use what you fixed? Do I just need to run `curl -Lo- https://goo.gl/C170k | bash` again?

**Comment by MarioRicalde** [comment]
First, make sure you double check the requirements:

![](http://doge.mx/wow/Window_18D48489.png)

If you're on a mac, you're going to need to install a new dependency. 

After you do that, you'll just need to run the installation script again, and you're ready!

**Comment by shinokada** [comment]
Good as gold. It works on Mac.

Thanks again for your work and time. 大変ありがとうございました。
