### ISSUE TITLE
Describe how to add or ignore generated footer

### ISSUE THREAD

**Issue by xolvo** [hybridgroup/GitHub-Wikifier#22]
I can't find any references about footer generation.
And also I wish to not generate this file. Or not for all pages... Is it possible?

**Comment by MarioRicalde** [comment]
Currently there's no option to hide the footer, other than deleting the following line:

https://github.com/hybridgroup/GitHub-Wikifier/blob/master/pre-commit#L159

That should do it.

I think that not showing the footer is bad, if you plan to be using the generator more than once, things are prone to be overridden easily.

Cheers.
