### ISSUE TITLE
Recursive Subdirectories

### ISSUE THREAD

**Issue by wintermeyer** [hybridgroup/GitHub-Wikifier#3]
I'm probably stretching it now but are recursive subdirectories possible? One more level would make sense for some stuff.

**Comment by MarioRicalde** [comment]
I definitely want to get this working. 

I think that one sub level would suffice.

How does this look?

## Documentation

### ☰ 1. Introduction
1. Getting Started
   1. Setting up Your Environment
   2. Setting up Your Heroku Account
2. Figuring out what issue to work on.
3. Proffit

### ☰ 2. Wiki Content
1. Write more Wiki Content
2. Be Happy
