### ISSUE TITLE
? in a filename

### ISSUE THREAD

**Issue by wintermeyer** [hybridgroup/GitHub-Wikifier#4]
The new version stumbles over a question mark (?) in the filename. No biggy but because no warning is shown it might be a problem for newbies.

**Comment by MarioRicalde** [comment]
Adding some documentation on this: https://github.com/hybridgroup/GitHub-Wikifier/wiki/1.2.2.-Naming-Files

( and much more ).

Honestly, I need to make a task for errors. But this is not a priority at the moment, will make new issue for it though.
