### ISSUE TITLE
recursive_write fatal error

### ISSUE THREAD

**Issue by atz** [hybridgroup/GitHub-Wikifier#5]
On given files, the script will crash with:
`recursive_write:10: job table full`

Possibly releated: executions on certain filenames (e.g. including a colon) will produce erroneous files, like:

```
./Data/Metrics-Client:-Attendance-Data.md.md
```

**Comment by MarioRicalde** [comment]
Thanks for helping!

Yes, this makes sense. There's some symbols that I need to add to the Regexp. Also, I need to write a little bit of documentation on the good practices for naming files.

Clone the current wiki, to see how you should name directories. You'll notice, subjects need to be in directories with the format:

```
1.-Subject/
  1.1-Title.md
  1.2-Title2.md
  1.3-Sub-Subject.md/
     1.3.1-Title.md
     1.3.2-Title2.md
```

Working on the documentation right now.

**Comment by MarioRicalde** [comment]
I need to add some error catching for incorrect file names, though.

**Comment by MarioRicalde** [comment]
Here, added some documentation:

https://github.com/hybridgroup/GitHub-Wikifier/wiki/1.2.2.-Naming-Files

Making an issue based on better error reporting.
