### ISSUE TITLE
problem with loading pre-commit

### ISSUE THREAD

**Issue by antass** [hybridgroup/GitHub-Wikifier#8]
Hi!

Thanks for taking the initiative to build a ToC for the wiki!

After downloading the pre-commit and making it executable (using your line of code), when I try to commit, I get this:

> **user@host:~/Dropbox/mywiki$** git add .
> **user@host:~/Dropbox/mywiki$** git commit -am "added pages; added wikifier"
> error: cannot run .git/hooks/pre-commit: No such file or directory

If I just `cd` into `.git/hooks`, I can see my `pre-commit`.

Any ideas?

Thanks,
Ania

**Comment by solojavier** [comment]
Have you tried using
`git add .`
and then commit without add option:
`git commit -m "message"`

?

**Comment by solojavier** [comment]
@antass are you still having the same issue?

**Comment by kaezarrex** [comment]
I'm having the same problem. Here is my directory structure if that helps:

```
.
├── 1.-Part-One
│   └── 1.1.-Introduction.md
└── Home.md
```

I'm on Ubuntu 12.04.2 using git version 1.7.9.5.

**Comment by kaezarrex** [comment]
I figured out my problem. The pre-commit hook depends on zsh, but I didn't have it installed.

**Comment by antass** [comment]
I have moved my wiki some place else, as I needed a private page. I just checked if `zsh` is installed on my Ubuntu 12.10 - it isn't, so it's possible that was the problem. I'll test it out and let you know.

**Comment by MarioRicalde** [comment]
Today we fixed some issues with Ubuntu + Zsh.

It was not working correctly, but now it is.
